In [35]:
import pandas as pd
import time
import torch

In [36]:
torch.__version__

'1.4.0+cpu'

## Загрузка данных

In [2]:
df = pd.read_csv('../data/data_lecture_6.csv')
df.head()

Unnamed: 0     id  episode_id  number  \
0           0  10368          35      29   
1           1  10369          35      30   
2           2  10370          35      31   
3           3  10372          35      33   
4           4  10374          35      35   

                                            raw_text  timestamp_in_ms  \
0           Lisa Simpson: Maggie, look. What's that?           235000   
1                    Lisa Simpson: Lee-mur. Lee-mur.           237000   
2                    Lisa Simpson: Zee-boo. Zee-boo.           239000   
3  Lisa Simpson: I'm trying to teach Maggie that ...           245000   
4  Lisa Simpson: It's like an ox, only it has a h...           254000   

   speaking_line  character_id  location_id raw_character_text  \
0           True             9          5.0       Lisa Simpson   
1           True             9          5.0       Lisa Simpson   
2           True             9          5.0       Lisa Simpson   
3           True             9          5.0       Lisa Simpson   
4           True             9          5.0       Lisa Simpson   

  raw_location_text                                       spoken_words  \
0      Simpson Home                         Maggie, look. What's that?   
1      Simpson Home                                  Lee-mur. Lee-mur.   
2      Simpson Home                                  Zee-boo. Zee-boo.   
3      Simpson Home  I'm trying to teach Maggie that nature doesn't...   
4      Simpson Home  It's like an ox, only it has a hump and a dewl...   

                                     normalized_text  word_count  
0                             maggie look whats that         4.0  
1                                    lee-mur lee-mur         2.0  
2                                    zee-boo zee-boo         2.0  
3  im trying to teach maggie that nature doesnt e...        24.0  
4  its like an ox only it has a hump and a dewlap...        18.0

In [3]:
phrases = df['normalized_text'].tolist()
phrases[:10]

['maggie look whats that',
 'lee-mur lee-mur',
 'zee-boo zee-boo',
 'im trying to teach maggie that nature doesnt end with the barnyard i want her to have all the advantages that i didnt have',
 'its like an ox only it has a hump and a dewlap hump and dew-lap hump and dew-lap',
 'you know his blood type how romantic',
 'oh yeah whats my shoe size',
 'ring',
 'yes dad',
 'ooh look maggie what is that do-dec-ah-edron dodecahedron']

In [37]:
text = [[c for c in ph] for ph in phrases if type(ph) is str]

In [45]:
len(text[0])

22

In [5]:
#len(text)
#text[:100]

## Делаем массив с данными

In [6]:
CHARS = set('abcdefghijklmnopqrstuvwxyz ')
INDEX_TO_CHAR = ['none'] + [w for w in CHARS]
CHAR_TO_INDEX = {w: i for i, w in enumerate(INDEX_TO_CHAR)}

In [7]:
INDEX_TO_CHAR

['none',
 'r',
 'e',
 't',
 'm',
 'g',
 'l',
 's',
 'w',
 'k',
 'd',
 'n',
 'a',
 'z',
 'p',
 'u',
 ' ',
 'y',
 'q',
 'v',
 'h',
 'b',
 'i',
 'x',
 'c',
 'j',
 'f',
 'o']

In [8]:
MAX_LEN = 50
X = torch.zeros((len(text), MAX_LEN), dtype=int)
for i in range(len(text)):
    for j, w in enumerate(text[i]):
        if j >= MAX_LEN:
            break
        X[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [16]:
X.shape

torch.Size([10891, 50])

In [19]:
#X.shape - torch.Size([10891, 50])
len(text[10])

74

In [11]:
X[0:10]

tensor([[ 4, 12,  5,  5, 22,  2, 16,  6, 27, 27,  9, 16,  8, 20, 12,  3,  7, 16,
          3, 20, 12,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  2,  2,  0,  4, 15,  1, 16,  6,  2,  2,  0,  4, 15,  1,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [13,  2,  2,  0, 21, 27, 27, 16, 13,  2,  2,  0, 21, 27, 27,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [22,  4, 16,  3,  1, 17, 22, 11,  5, 16,  3, 27, 16,  3,  2, 12, 24, 20,
         16,  4, 12,  5,  5, 22,  2, 16,  3, 20, 12,  3, 16, 11, 12,  3, 15,  1,
          2, 16, 10, 27,  2,  7, 11,  3, 16,  2, 11, 10, 16,  8],
        [22,  3,  7, 16,  6, 22,  9,  2, 16, 12, 11, 16, 27, 23, 16, 27, 11,  6,
       

## Смотрим на Embedding и RNN ячейку

In [23]:
len(INDEX_TO_CHAR)

28

In [69]:
len(t)

10

In [72]:
X[0:10]

tensor([[ 4, 12,  5,  5, 22,  2, 16,  6, 27, 27,  9, 16,  8, 20, 12,  3,  7, 16,
          3, 20, 12,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6,  2,  2,  0,  4, 15,  1, 16,  6,  2,  2,  0,  4, 15,  1,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [13,  2,  2,  0, 21, 27, 27, 16, 13,  2,  2,  0, 21, 27, 27,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [22,  4, 16,  3,  1, 17, 22, 11,  5, 16,  3, 27, 16,  3,  2, 12, 24, 20,
         16,  4, 12,  5,  5, 22,  2, 16,  3, 20, 12,  3, 16, 11, 12,  3, 15,  1,
          2, 16, 10, 27,  2,  7, 11,  3, 16,  2, 11, 10, 16,  8],
        [22,  3,  7, 16,  6, 22,  9,  2, 16, 12, 11, 16, 27, 23, 16, 27, 11,  6,
       

In [78]:
embeddings = torch.nn.Embedding(len(INDEX_TO_CHAR), 28 )
t = embeddings(X[0:10])
t

tensor([[[ 0.1135, -2.0520, -0.6744,  ..., -1.1082, -0.6738,  0.3353],
         [-0.3136,  2.8690,  1.4715,  ...,  0.8266, -1.3556,  0.5348],
         [ 1.6188,  0.1199, -0.4861,  ..., -0.3791,  1.9911, -1.0539],
         ...,
         [-0.8125, -0.9285,  2.1825,  ...,  0.9743,  0.8143,  1.0269],
         [-0.8125, -0.9285,  2.1825,  ...,  0.9743,  0.8143,  1.0269],
         [-0.8125, -0.9285,  2.1825,  ...,  0.9743,  0.8143,  1.0269]],

        [[-0.4081, -0.3122,  0.6786,  ..., -1.9413, -1.3147,  0.1558],
         [ 1.3474, -0.7706, -1.4374,  ...,  1.1907, -0.6472,  0.3419],
         [ 1.3474, -0.7706, -1.4374,  ...,  1.1907, -0.6472,  0.3419],
         ...,
         [-0.8125, -0.9285,  2.1825,  ...,  0.9743,  0.8143,  1.0269],
         [-0.8125, -0.9285,  2.1825,  ...,  0.9743,  0.8143,  1.0269],
         [-0.8125, -0.9285,  2.1825,  ...,  0.9743,  0.8143,  1.0269]],

        [[ 2.0098,  0.9833, -2.3721,  ..., -1.8541,  0.9063, -0.3808],
         [ 1.3474, -0.7706, -1.4374,  ...,  1

In [80]:
t.shape, X[0:10].shape

(torch.Size([10, 50, 28]), torch.Size([10, 50]))

In [81]:
rnn = torch.nn.RNN(28, 128, batch_first=True)
o, s = rnn(t)
o.shape, s.shape

(torch.Size([10, 50, 128]), torch.Size([1, 10, 128]))

In [28]:
o, s2 = rnn(t, s)
o.shape, s2.shape

(torch.Size([10, 50, 128]), torch.Size([1, 10, 128]))

## Практика. Реализуйте код модели нейронной сети
3 слоя - embeding (28), скрытая ячейка (128), полносвязанный из состояния rnn в букву (28)

In [48]:
sents = X[0:10]
sents.shape

torch.Size([10, 50])

In [49]:
embds = embeddings(sents)
embds.shape

torch.Size([10, 50, 28])

In [50]:
o, s = rnn(embds)
o.shape

torch.Size([10, 50, 128])

In [51]:
lin = torch.nn.Linear(128, 28)

In [52]:
lin(o.reshape(-1, 128)).shape

torch.Size([500, 28])

In [54]:
class Network(torch.nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.embeddings = torch.nn.Embedding(len(INDEX_TO_CHAR), 28)
        self.rnn = torch.nn.RNN(28, 128, batch_first=True)
        self.linear = torch.nn.Linear(128, 28)
        
    def forward(self, sentences, state=None):
        embds = self.embeddings(sentences)
        out, new_state = self.rnn(embds, state)
        result = self.linear(out)
        return result, new_state

In [55]:
model = Network()

In [56]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=.05)

In [57]:
for ep in range(10):
    start = time.time()
    train_loss = 0.
    train_passed = 0

    for i in range(int(len(X) / 100)):
        batch = X[i * 100:(i + 1) * 100]
        X_batch = batch[:, :-1]
        Y_batch = batch[:, 1:].flatten()

        optimizer.zero_grad()
        answers, _ = model.forward(X_batch)
        answers = answers.view(-1, len(INDEX_TO_CHAR))
        loss = criterion(answers, Y_batch)
        train_loss += loss.item()

        loss.backward()
        optimizer.step()
        train_passed += 1

    print("Epoch {}. Time: {:.3f}, Train loss: {:.3f}".format(ep, time.time() - start, train_loss / train_passed))

Epoch 0. Time: 5.071, Train loss: 2.087
Epoch 1. Time: 6.153, Train loss: 1.810
Epoch 2. Time: 6.693, Train loss: 1.733
Epoch 3. Time: 6.816, Train loss: 1.690
Epoch 4. Time: 6.603, Train loss: 1.659
Epoch 5. Time: 6.621, Train loss: 1.635
Epoch 6. Time: 6.689, Train loss: 1.615
Epoch 7. Time: 6.720, Train loss: 1.597
Epoch 8. Time: 6.656, Train loss: 1.582
Epoch 9. Time: 6.651, Train loss: 1.568


## Практика. Реализуйте код генерации следующей буквы на основе модели
Логика такая:
    - Сначала кормим в нее буквы из sentence (прогревая состояние)
    - Затем пока не получим none (0) берем самую вероятную букву и добавляем ее в sentence
    - Повторяем

In [82]:
def generate_sentence():
    sentence = ['h', 'e', 'l', 'l', 'o']
    #sentence = ['m', 'y', 'n', 'a', 'm', 'e', 'i', 's']
    state = None
    for i in range(MAX_LEN):
        X = torch.Tensor([[CHAR_TO_INDEX[sentence[i]]]]).type(torch.long)
        result, state = model.forward(X, state)
        prediction = result[0, -1, :]
        index = prediction.argmax()
        if i >= 4:
            if index == 0:
                break
            sentence.append(INDEX_TO_CHAR[index])
    print(''.join(sentence))

In [83]:
generate_sentence()

hello the so the the the the the the the the the th


In [84]:
for ep in range(10):
    start = time.time()
    train_loss = 0.
    train_passed = 0

    for i in range(int(len(X) / 100)):
        batch = X[i * 100:(i + 1) * 100]
        X_batch = batch[:, :-1]
        Y_batch = batch[:, 1:].flatten()

        optimizer.zero_grad()
        answers, _ = model.forward(X_batch)
        answers = answers.view(-1, len(INDEX_TO_CHAR))
        loss = criterion(answers, Y_batch)
        train_loss += loss.item()

        loss.backward()
        optimizer.step()
        train_passed += 1

    print("Epoch {}. Time: {:.3f}, Train loss: {:.3f}".format(ep, time.time() - start, train_loss / train_passed))
    generate_sentence()

Epoch 0. Time: 4.932, Train loss: 1.409
hello the so the the the the the the the the the th
Epoch 1. Time: 4.987, Train loss: 1.404
hello the the the the the the the the the the the t
Epoch 2. Time: 4.905, Train loss: 1.400
hello the the the the the the the the the the the t


KeyboardInterrupt: 